### ISSUE TITLE
Add post model

### ISSUE THREAD

**Issue by churichard** [SpecialHaven/SpecialHaven#3]
Should have at least the following attributes:
1. Title
2. Author (ID of the user)
3. Content (the actual post itself)
4. Type (text, event, link, video, etc.)

**Comment by mitchbregs** [comment]
- category/filter (ie; #autism, #musculardystrophy)

**Comment by michaelcbarrett** [comment]
Regarding image uploads, are we going to use Amazon Web Services for cloud storage? Or should I just have the image posts point to a remote URL for now?

**Comment by churichard** [comment]
Let's use a remote url for now. We can integrate AWS later on.
