### ISSUE TITLE
Add the ability to favorite a post

### ISSUE THREAD

**Issue by churichard** [SpecialHaven/SpecialHaven#32]
- Add "heart" button to each post view. The heart should be transparent when it hasn't been clicked, and red when it has been clicked. If it is clicked again, it should turn transparent again. There should be a number below the heart that shows the global number of favorites that the post has.
- The "heart" button should increment the number of favorites that the Post has when it has been clicked. If it is clicked again, it should decrement the number of favorites the Post has.
- Persistence: If the heart is red, it should stay red if the user refreshes the page, navigates elsewhere and comes back, or logs out.

**Comment by mitchbregs** [comment]
can u throw this up on heroku?

**Comment by michaelcbarrett** [comment]
It's up on heroku now

https://desolate-spire-3042.herokuapp.com/

**Comment by mitchbregs** [comment]
Awesome thank u

On Friday, January 15, 2016, michaelcbarrett notifications@github.com
wrote:

> It's up on heroku now
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpecialHaven/SpecialHaven/issues/32#issuecomment-172134368
> .

## 

Mitch
