### ISSUE TITLE
EventPost form is missing location

### ISSUE THREAD

**Issue by churichard** [SpecialHaven/SpecialHaven#36]
When you create a new EventPost, the form is missing the box to put in a location. This should be added.

Also, the view for the EventPost (when you click on an EventPost in the timeline) should be adjusted to show the location.

**Comment by michaelcbarrett** [comment]
Right now the zip code is being stored as the location. Should it be separate? I guess I wasn't sure how we should handle the location (city and state, coordinates via an embedded map, address?)

**Comment by mitchbregs** [comment]
Definitely no address. I think city and state is great.

On Thursday, January 21, 2016, michaelcbarrett notifications@github.com
wrote:

> Right now the zip code is being stored as the location. Should it be
> separate? I guess I wasn't sure how we should handle the location (city and
> state, coordinates via an embedded map, address?)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpecialHaven/SpecialHaven/issues/36#issuecomment-173790326
> .

## 

Mitch

**Comment by michaelcbarrett** [comment]
Ok, great

**Comment by churichard** [comment]
Why city and state? If people are actually planning on going to these events, then they'll need to have an address to go to.

**Comment by mitchbregs** [comment]
Oh crap I thought this was user sign up - can we integrate maps API to this

On Thursday, January 21, 2016, Richard Chu notifications@github.com wrote:

> Why city and state? If people are actually planning on going to these
> events, then they'll need to have an address to go to.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/SpecialHaven/SpecialHaven/issues/36#issuecomment-173800304
> .

## 

Mitch

**Comment by churichard** [comment]
Yeah, I think the Google Places API is the way to go for this (specifically Place Autocomplete): https://developers.google.com/places/javascript/

**Comment by michaelcbarrett** [comment]
Perfect, thanks for providing the link
