### ISSUE TITLE
Add user profile

### ISSUE THREAD

**Issue by churichard** [SpecialHaven/SpecialHaven#5]
The profile page should be relatively simple:
1. Name
2. User type
3. Email
4. Picture
5. Description
6. List of all user posts

**Comment by mitchbregs** [comment]
what are we doing in terms of user types

**Comment by churichard** [comment]
User types should be one of the following:
1. Caretaker
2. Expert
3. Non-profit
4. Business

We can also show that on the profile page if we want.

**Comment by mitchbregs** [comment]
awesome

**Comment by mitchbregs** [comment]
whats better "Expert" or "Professional" lol

**Comment by churichard** [comment]
We can keep it as "Expert" for now :+1:
