### ISSUE TITLE
Add timeline

### ISSUE THREAD

**Issue by churichard** [SpecialHaven/SpecialHaven#6]
The timeline should show a list of all user posts, for now. We can add a filtering system later.

**Comment by mitchbregs** [comment]
worry about filtering later... something we need to cosider is a timeline subclass sort of thing where if someone clicks on #autism it takes them to the autism timeline ("subreddit","subclass")

**Comment by churichard** [comment]
Yep, we can do that. We should set up a global timeline first which will show all of the posts that anyone has ever made on the website. Everything after that (different tags, showing only recent posts, etc.) is essentially just different filtering systems.

**Comment by mitchbregs** [comment]
gotcha -- would that be a different page or just a query? i see these being preset pages "specialhaven.com/autism" and we'd probably want them cutomizable

**Comment by churichard** [comment]
We can definitely have the tags be on preset pages, but it would probably just be fetching the posts with a filter, which should be fine with small numbers of posts. If we find that that's getting too slow, we can always cache the different tags into different database tables.

**Comment by mitchbregs** [comment]
ok cool :) zendesk is sweeeet
